' Copyright © exc-jdbi 2016
'
' © mnBase64 2016
'
' mnBase64 - www.github.com/exc-jdbi/base64
'
' mnBase64 is Free and Opensource Software

Option Strict On
Option Explicit On


'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.34209
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

