' Copyright © exc-jdbi 2016
'
' © mnBase64 2016
'
' mnBase64 - www.github.com/exc-jdbi/base64
'
' mnBase64 is Free and Opensource Software

Option Strict On
Option Explicit On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
